version: "3"
services:
  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "data1:/data"
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "data1"
